app/__init__.py
from flask import Flask

app = Flask(__name__)

# from app import views1

from app.views import pages
from app.views import demo1
from app.views import demo2

app.register_blueprint(pages.mod)
app.register_blueprint(demo1.mod, url_prefix='/demo1')
app.register_blueprint(demo2.mod, url_prefix='/demo2')

app/views/demo1.py
from flask import Blueprint
from flask import render_template, jsonify, request, redirect, url_for

mod = Blueprint('demo1', __name__, )


@mod.route('/', methods=["GET", "POST"])
def index():
    return redirect(url_for('demo1.editor'))


@mod.route('/editor', methods=["GET", "POST"])
def editor():
    return render_template('demo1.html')


@mod.route('/fetch', methods=["GET", "POST"])
def fetch_file():
    filepath = request.args.get('path')
    if not filepath:
        return "No path passed", 403
    try:
        content = open(filepath, "rb").read()
    except:
        return "Error reading file", 403

    return jsonify(content=content)


@mod.route('/save', methods=["GET", "POST"])
def save_file():
    filepath = request.args.get('path')
    content = request.args.get('content')

    if not filepath:
        return "No path passed", 403

    if not content:
        return "No content passed", 403

    try:
        with open(filepath, "wb") as f:
            f.write(content)
            message = "File saved successfully"
    except:
        return "Error writing file", 403

    return jsonify(content=message)

app/views/demo2.py
from flask import Blueprint
from flask import render_template, request, make_response

mod = Blueprint('demo2', __name__, )


@mod.route('/', methods=["GET"])
def index():
    return render_template('demo2_input.html')


@mod.route('/download', methods=['POST'])
def download():
    filename = request.form.get('filename')
    content = request.form.get('content')
    if not content:
        return "No content passed", 403

    if not filename:
        return "No filename passed", 403

    response = make_response(content)
    response.headers["Content-Disposition"] = "attachment;filename=" + filename
    return response


@mod.route('/editor', methods=["POST"])
def editor():
    highlighter_map = {
        'yaml': 'yaml',
        'yml': 'yaml'
    }
    datafile = request.files.get('datafile')

    filename = datafile.filename
    fileext = filename.split('.')[-1]
    content = datafile.read()
    highlighter = highlighter_map.get(fileext) or "default"

    return render_template('demo2.html', content=content,
                           highlighter=highlighter)

app/views/pages.py
from flask import Blueprint, render_template

mod = Blueprint('pages', __name__, )


@mod.route('/', methods=["GET", "POST"])
def index():
    return render_template('index.html')

app/templates/boilerplate.html
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Edotor by Arpit Bhayani</title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/ico" href="/static/images/favicon.ico">

    <link rel="stylesheet" href="/static/semantic/dist/semantic.min.css">

    <!-- JS Libs -->
    <script src="/static/js/lib/jquery-1.11.3.min.js"></script>
    <script src="/static/semantic/dist/semantic.min.js"></script>

    <!-- UX Styling -->
    <link rel="stylesheet" href="/static/css/ux.css">

</head>

<body>
    <div id="error-zone" class="ui top sidebar">
        <div id="error-msg" class="ui negative message header large"></div>
    </div>
    <div id="alert-zone" class="ui top sidebar">
        <div id="alert-msg" class="ui positive message header large"></div>
    </div>
    <div class="overlay">
        {% block content %}{% endblock %}
    </div>
</body>
{% block head %}{% endblock %}
</html>

app/templates/demo1.html
{% extends "boilerplate.html" %}

{% block content %}
<div class="ui top attached borderless menu">
    <div class="ui large header item">
        <img src="/static/images/logo.png">
        &nbsp; <a href="/">Edotor</a>
    </div>
    <div class="right menu">
        <div class="item ui header">
            <h4 id="open_file_form_filepath"></h4>
        </div>
        <div class="item">
            <select class="ui search dropdown" name="filetype" id="open_file_form_update_mode_dropdown">
                <option value="">Choose Highlighter</option>
                <option value="javascript">Javascript</option>
                <option value="yaml">YAML</option>
            </select>
        </div>
        <div class="item">
            <div class="ui buttons">
                <div class="ui button basic orange" id="open_file_form_diff_button">Toggle Diff</div>
                <div class="ui button basic green" id="open_file_form_save_button"><i class="save icon"></i>Save</div>
            </div>
        </div>
    </div>
</div>
<div class="ui grid">
    <div class="four wide column">
        <div class="ui basic segment">
            <div class="ui form" id="open_file_form">
                <div class="required small field">
                    <label>Complete file path</label>
                    <div class="ui icon input">
                        <input type="text" name="filepath" placeholder="Absolute file path"/>
                        <i class="file icon"></i>
                    </div>
                </div>
                <div class="field">
                    <input type="button" id="open_file_form_submit_button" class="ui button basic orange" value="Open in editor"/>
                </div>
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        <textarea id="online_editor"></textarea>
    </div>
    <div class="twelve wide column">
        <div id="compare"></div>
    </div>
</div>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/css/codemirror.css">
<link rel="stylesheet" href="/static/css/mergely.css">

<script src="/static/js/lib/codemirror.js"></script>
<script src="/static/js/lib/codemirror_modes/yaml.js"></script>
<script src="/static/js/lib/codemirror_modes/javascript.js"></script>
<script src="/static/js/lib/mergely.min.js"></script>
<script src="/static/js/demo1.js"></script>
{% endblock %}

app/templates/demo2.html
{% extends "boilerplate.html" %}

{% block content %}
<div class="ui top attached borderless menu">
    <div class="ui large header item">
        <img src="/static/images/logo.png">
        &nbsp; <a href="/">Edotor</a>
    </div>
    <div class="right menu">
        <div class="item">
            <div class="ui buttons">
                <div class="ui button basic red" id="revert_original_button"><i class="angle double left icon"></i>Revert to original</div>
                <div class="ui button basic orange" id="revert_last_saved_button"><i class="angle left icon"></i>Revert to last saved</div>
                <div class="ui button basic green" id="save_button"><i class="save icon"></i>Save</div>
                <div class="ui button basic blue" id="download_button"><i class="download icon"></i>Download</div>
            </div>
        </div>
    </div>
</div>
<div class="ui grid">
    <div style="display: none;" id="highlighter">{{highlighter}}</div>
    <div style="display: none;" id="original_content">{{content}}</div>
    <div style="display: none;" id="last_saved_content">{{content}}</div>
    <!-- <div class="row center aligned">
        <div class="sixteen wide column">
            <div class="ui grey segment basic inverted header">
                <h4>Live Diff View</h4>
            </div>
        </div>
    </div> -->
    <div class="row center aligned">
        <div class="eight wide column">
            <div class="ui segment brown basic header">
                Original Contents (Readonly)
            </div>
        </div>
        <div class="eight wide column">
            <div class="ui segment brown basic header">
                Edit here
            </div>
        </div>
    </div>
    <div class="row" style="padding: 0px !important;">
        <div style="width: 100%; padding-left: 2%; padding-right: 2%;">
            <div id="compare"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/css/codemirror.css">
<link rel="stylesheet" href="/static/css/mergely.css">

<script src="/static/js/lib/codemirror.js"></script>
<script src="/static/js/lib/codemirror_modes/yaml.js"></script>
<script src="/static/js/lib/codemirror_modes/javascript.js"></script>
<script src="/static/js/lib/mergely.min.js"></script>
<script src="/static/js/demo2.js"></script>
{% endblock %}

app/templates/demo2_input.html
{% extends "boilerplate.html" %}

{% block content %}
<div class="ui top attached borderless menu">
    <div class="ui large header item">
        <img src="/static/images/logo.png">
        &nbsp; <a href="/">Edotor</a>
    </div>
</div>
<div class="ui divider hidden"></div>
<div class="ui middle aligned grid child">
    <div class="column">
        <div class="ui center aligned page grid">
            <div class="eight wide column">
                <div class="ui left aligned segment">
                    <h4 class="ui dividing header">Open File to edit</h4>
                    <form class="ui form" method="POST" enctype="multipart/form-data" action="{{url_for('demo2.editor')}}">
                        <div class="field">
                            <label for="datafile">Datafile</label>
                            <div class="ui icon input">
                                <input type="file" name="datafile" file="datafile"/>
                            </div>
                        </div>
                        <input type="submit" name="submit" value="Open" class="ui inverted blue button" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/css/codemirror.css">
<link rel="stylesheet" href="/static/css/mergely.css">

<script src="/static/js/lib/codemirror.js"></script>
<script src="/static/js/lib/codemirror_modes/yaml.js"></script>
<script src="/static/js/lib/codemirror_modes/javascript.js"></script>
<script src="/static/js/lib/mergely.min.js"></script>
<script src="/static/js/demo2.js"></script>
{% endblock %}

app/templates/editor.html
{% extends "boilerplate.html" %}

{% block content %}
<div class="ui top attached borderless menu">
    <div class="large header item">
        <img src="/static/images/logo.png">
        &nbsp; <a href="/">Editor Demo</a>
    </div>
    <div class="right menu">
        <div class="item ui header">
            <h4 id="open_file_form_filepath"></h4>
        </div>
        <div class="item">
            <select class="ui search dropdown" name="filetype" id="open_file_form_update_mode_dropdown">
                <option value="">Choose Highlighter</option>
                <option value="javascript">Javascript</option>
                <option value="yaml">YAML</option>
            </select>
        </div>
        <div class="item">
            <div class="ui buttons">
                <div class="ui button basic orange" id="open_file_form_diff_button">Toggle Diff</div>
                <div class="ui button basic green" id="open_file_form_save_button"><i class="save icon"></i>Save</div>
            </div>
        </div>
    </div>
</div>
<div class="ui grid">
    <div class="four wide column">
        <div class="ui basic segment">
            <div class="ui form" id="open_file_form">
                <div class="required small field">
                    <label>Complete file path</label>
                    <div class="ui icon input">
                        <input type="text" name="filepath" placeholder="Absolute file path"/>
                        <i class="file icon"></i>
                    </div>
                </div>
                <div class="field">
                    <input type="button" id="open_file_form_submit_button" class="ui button basic orange" value="Open in editor"/>
                </div>
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        <textarea id="online_editor"></textarea>
    </div>
    <div class="twelve wide column">
        <div id="compare"></div>
    </div>
</div>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="/static/css/codemirror.css">
<link rel="stylesheet" href="/static/css/mergely.css">

<script src="/static/js/lib/codemirror.js"></script>
<script src="/static/js/lib/codemirror_modes/yaml.js"></script>
<script src="/static/js/lib/codemirror_modes/javascript.js"></script>
<script src="/static/js/lib/mergely.min.js"></script>
<script src="/static/js/editor.js"></script>
{% endblock %}

app/templates/index.html
{% extends "boilerplate.html" %}

{% block content %}
    <div class="ui hidden divider"></div>
    <div class="ui middle aligned">
        <img class="ui centered small image" src="/static/images/logo.png">
        <h2 class="ui header center aligned">Edotor</h2>
        <h4 class="ui header center aligned">By <a href="https://github.com/arpitbbhayani/">Arpit Bhayani</a></h4>
    </div>
    <div class="ui hidden divider"></div>
    <div class="ui center aligned basic segment">
        <div class="ui horizontal list">
            <div class="item">
                <h2 class="ui header  small"><u><a href="{{url_for('demo1.index')}}">Demo 1</a></u></h2>
            </div>
            <div class="item">
                <h2 class="ui header  small"><u><a href="{{url_for('demo2.index')}}">Demo 2</a></u></h2>
            </div>
        </div>
    </div>
{% endblock %}

{% block head %}
<script src="/static/js/index.js"></script>
{% endblock %}